pipeline {
    agent any
    tools {
        maven 'maven'
    }
    environment {
        NEXUS_URL = 'http://localhost:8081'  // Change if Nexus is on a different host
        NEXUS_REPOSITORY = 'maven-releases'
        ARTIFACT_GROUP = 'com.example.laundry'
        ARTIFACT_ID = 'LaundryApp'
        ARTIFACT_VERSION = '1.1.1'
        ARTIFACT_FILE = "target/LaundryApp-1.0-SNAPSHOT.jar"
        NEXUS_CREDENTIALS = 'jenkins-pat'  // Ensure credentials exist in Jenkins
    }
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'jenkinsfile', credentialsId: 'jenkins-pat', url: 'https://github.com/adityabhatia1999/chavva.git'
            }
        }

        stage('Build') {
            steps {
                dir('apps') {
                    script {
                        sh 'pwd'
                        sh 'ls'
                        sh 'mvn --version'
                        sh 'mvn clean compile'
                    }
                }
            }
        }

        stage('Test') {
            steps {
                dir('apps') {
                    script {
                        sh 'mvn test'
                    }
                }
            }
        }

        stage('Package') {
            steps {
                dir('apps') {
                    script {
                        sh 'mvn package'
                    }
                }
            }
        }

        stage('Upload to Nexus') {
            steps {
                dir('apps') {
                    script {
                        withCredentials([usernamePassword(credentialsId: "${NEXUS_CREDENTIALS}", usernameVariable: 'NEXUS_USER', passwordVariable: 'NEXUS_PASS')]) {
                            sh """
                            mvn deploy:deploy-file \
                                -Durl=${NEXUS_URL}/repository/${NEXUS_REPOSITORY}/ \
                                -DrepositoryId=nexus \
                                -Dfile=${ARTIFACT_FILE} \
                                -DgroupId=${ARTIFACT_GROUP} \
                                -DartifactId=${ARTIFACT_ID} \
                                -Dversion=${ARTIFACT_VERSION} \
                                -Dpackaging=jar \
                                -DgeneratePom=true \
                                --settings ./settings.xml
                            """
                        }
                    }
                }
            }
        }

        stage('CD Deploy to Server') {
            steps {
                script {
                    sh """
                    echo "Downloading artifact from Nexus..."
                    curl -u admin:admin -o ${ARTIFACT_ID}-${ARTIFACT_VERSION}.jar \
                    ${NEXUS_URL}/repository/${NEXUS_REPOSITORY}/${ARTIFACT_GROUP.replace('.', '/')}/${ARTIFACT_ID}/${ARTIFACT_VERSION}/${ARTIFACT_ID}-${ARTIFACT_VERSION}.jar
                    """
                }
            }
        }
    }
}

